### ISSUE TITLE
Unable to run the project locally. main.py and requirements.txt files missing

### ISSUE THREAD

**Issue by parth-mansata** [ActivityWatch/aw-server#69]
I tried to run the [project](https://github.com/ActivityWatch/aw-server/tree/32a201a6aeb1c8ea688373d59a2340fd701863e8) locally.
I was facing issue to start the project and debugged that to start the project, main.py and requirements.txt files are required which are missing. Can somebody guide which is the correct branch to setup the project. 

Many thanks in advance for the help.

**Comment by ErikBjare** [comment]
There is no requirements.txt because requirements are handled by poetry. You can install it using poetry with `poetry install` or with `pip install .`, after which you should have aw-server available in your PATH. Alternatively you could do `poetry run python3 -m aw_server` (or without poetry: `python3 -m aw_server`)
