### ISSUE TITLE
[Suggestion] Oracle Cloud Setup Tutorial

### ISSUE THREAD

**Issue by 2br-2b** [ActivityWatch/aw-server#70]
Matrix.org has a tutorial to make a free small server for their service: https://matrix.org/docs/guides/free-small-matrix-server/

Is there a simple setup like this that could be used for ActivityWatch? If so, could someone write one such tutorial, or do you just need to run the python program?

Even if not, the pricing comparison they show could be useful to have somewhere:

Vendor | Time-limit | Count | RAM (GB) | Storage (GB) | Transfer (GB)
-- | -- | -- | -- | -- | --
AWS | 12 months | 1 t2.micro | 1 | 30 | 15
Azure | 12 months | 1 B1S | 1 | 2x 64 | 15
GCP | no limit | 1 f1-micro | 0.6 | 30 | 1
Oracle | no limit | 2 VM.Standard.E2.1.Micro | 1 | 100 | 10000

**Comment by johan-bjareholt** [comment]
aw-server is currently not secure to run anywhere else than on a local machine, while it's possible to run aw-server on a remote machine there's no security or encryption in place so everything will just be exposed.

If you wanted to do it anyway, it's the same steps for installing as usual as we support linux and aw-server in a headless mode if you only start aw-server instead of aw-qt. There are lots of posts on the forum and on github issues on how to change so the watchers reports to a remote server.
