### ISSUE TITLE
High amount of I/O usage

### ISSUE THREAD

**Issue by theKAKAN** [ActivityWatch/aw-server#79]
Hello, I've been using AW and I love it.  
However, just today, I checked my I/O accumulated stats using `iotop -ao`  
It seems like `aw-server` used about 1GB/5mins. That, for a consumer SSD, is way above the the average daily usage, which is probably about 20-40GB/day.  

It could also be that I'm running many applications, with the browser plugin enabled which in turn is the cause for so much I/O usage. But, still, I think the team should try and do something about it...  

One, we could increase the default hearbeat/data-send intervals, or we could store the data to a temporary place and update it on disk every 10mins or so. I think the 2nd could be provided as a configuration option, if not given already.

It's possible to do the 2nd one manually, but I still hope it's something to consider. Either for this, or for the upcoming aw-server-rust rewrite!

![image](https://user-images.githubusercontent.com/22027824/120684583-63945e00-c48e-11eb-9061-621db6d072ef.png)

That is the data usage for about 2mins of monitoring( _time manually measured_ ). For firefox, there's an [config option](https://www.servethehome.com/firefox-is-eating-your-ssd-here-is-how-to-fix-it/) which can hugely reduce its usage( _which I'll go do after this_ ), but I'm not sure if anything similar exists for aw-server or its' plugins

**Comment by johan-bjareholt** [comment]
aw-server-rust has improvements to disk usage, you could try that out. It only writes to disk once every 15 seconds or once every 100 events whichever occurs first rather than writing to disk on every event.
It was improved this way to reduce I/O activity (waking up HDD/SSD etc.). Will likely also lower the amount of data written too, but have not measured that myself.

Would be possible to make those 15sec/100events configurable in the future, but the risk of doing so would be that the data would be lost if the computer suddenly shuts down or aw-server-rust crashes.

**Comment by theKAKAN** [comment]
Thank you. I'll try it out sometime.  
Also, yeah, while I do get that there would be a risk of losing data, I think I'd still love to be able to configure them according to my needs.  

I'll mark this as closed, then. Thank you.
